# see example config here: https://github.com/adityatelange/hugo-PaperMod/blob/7e5d17f08ac68ef7a365ba63d2f34a8c9f3a962a/config.yml

baseURL: https://blog.birki.io/
languageCode: en-us
title: 📖 blog
theme: [hugo-video, PaperMod]

paginate: 15
enableEmoji: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  # https://gohugo.io/getting-started/configuration-markup/#goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

  # https://gohugo.io/getting-started/configuration-markup/#highlight
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: monokai
    tabWidth: 4

params:
  env: production
  author: Grant Birkinbine
  defaultTheme: auto

  homeInfoParams:
    Title: blog.birki.io
    Content: >
      #### About

      - 👤 Grant Birkinbine's personal blog / journal / web posts

      - 📓 A collection of thoughts, photos, and memories from life.

      - 🌍 This blog contains stories about travels, things, places, and everything in between.

      ---

      - It should be noted that I am no writer and this is not an actual "blog" by any means. It is is mostly a way to save some thoughts and memories from travels and things that I do. It provides an easy means to share them with friends and family as well!

      ---

      📖 To read a post below, simply click anywhere on the cover image or it's description. Enjoy!

  cover:
    linkFullImages: false # don't make cover images clickable. Leads to bad UX

  # ---- opengraph ----
  title: Grant Birkinbine's Blog
  description: blog / journal / web posts
  images:
    - default.png
  # ------- end -------

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  displayFullLangName: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowBreadCrumbs: true
  ShowToc: true # table of contents on blog posts
  # comments: false
  # images: ["papermod-cover.png"]

  socialIcons:
    - name: github
      url: "https://github.com/GrantBirki/blog"
    - name: linkedin
      url: "https://www.linkedin.com/in/grantbirkinbine/"
    - name: twitter
      url: "https://twitter.com/grantbirki"
    - name: instagram
      url: "https://instagram.com/grantbirki"

  # editPost:
  #   URL: "https://github.com/GrantBirki/blog/tree/main/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

# menu:
#   main:
#     - identifier: about
#       name: 💡 about
#       url: /about/
#       weight: 10
#     - identifier: tags
#       name: 🏷️ tags
#       url: /tags/
#       weight: 20
#     - identifier:
#       name: ⭐ featured
#       url: /featured/
#       weight: 30
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 40
